/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#051424',
        'primary': '#8ed5ff',
        'on-primary': '#00354a',
        'primary-container': '#38bdf8',
        'primary-fixed': '#c4e7ff',
        'primary-fixed-dim': '#7bd0ff',
        'on-primary-fixed': '#001e2c',
        'on-primary-fixed-variant': '#004c69',
        'secondary': '#4edea3',
        'on-secondary': '#003824',
        'secondary-container': '#00a572',
        'on-secondary-container': '#00311f',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary': '#ffbcb7',
        'on-tertiary': '#68000a',
        'tertiary-container': '#ff938c',
        'on-tertiary-container': '#8d0012',
        'tertiary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-tertiary-fixed': '#410004',
        'on-tertiary-fixed-variant': '#930013',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#051424',
        'on-background': '#d4e4fa',
        'surface-dim': '#051424',
        'surface-bright': '#2c3a4c',
        'surface-container-lowest': '#010f1f',
        'surface-container-low': '#0d1c2d',
        'surface-container': '#122131',
        'surface-container-high': '#1c2b3c',
        'surface-container-highest': '#273647',
        'surface-variant': '#273647',
        'on-surface': '#d4e4fa',
        'on-surface-variant': '#bdc8d1',
        'outline': '#87929a',
        'outline-variant': '#3e484f',
        'inverse-surface': '#d4e4fa',
        'inverse-on-surface': '#233143',
        'inverse-primary': '#00668a',
        'surface-tint': '#7bd0ff',
        'surface-base': '#111827',
        'surface-raised': '#1E293B',
        'surface-elevated': '#27354A',
        'bg-app': '#0B0F19',
        'border-subtle': '#1E293B',
        'border-strong': '#334155',
        'border-interactive': '#475569',
        // Consumer-facing (bank simulation)
        'consumer-bg': '#F8FAFC',
        'consumer-surface': '#FFFFFF',
        'consumer-text-primary': '#0F172A',
        'consumer-text-secondary': '#64748B',
        'consumer-border': '#E2E8F0',
        // Status
        'status-warning': '#F59E0B',
        'status-warning-bg': 'rgba(245, 158, 11, 0.12)',
        'status-success-bg': 'rgba(16, 185, 129, 0.12)',
        'status-trace-bg': 'rgba(56, 189, 248, 0.12)',
        'status-danger-bg': 'rgba(239, 68, 68, 0.12)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'sidebar-compact': '16rem',
        'inspector-width': '24rem',
        'pane-header': '2.75rem',
      },
      fontFamily: {
        'body-sm':     ['Inter'],
        'body-base':   ['Inter'],
        'body-medium': ['Inter'],
        'title-sm':    ['Inter'],
        'headline-md': ['Space Grotesk'],
        'headline-lg': ['Space Grotesk'],
        'display-lg':  ['Space Grotesk'],
        'code-sm':     ['JetBrains Mono'],
        'code-base':   ['JetBrains Mono'],
        'label-caps':  ['JetBrains Mono'],
      },
      fontSize: {
        'body-sm':     ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-base':   ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-medium': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'title-sm':    ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-lg':  ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'code-sm':     ['11px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '500' }],
        'code-base':   ['13px', { lineHeight: '18px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'label-caps':  ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
